config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # par défaut nous sommes dans le cas du renter :
  resources :costumes, only: [:index, :show] do
    resources :bookings, only: :create
  end

  resources :bookings, only: [:index, :show]

  # profile utilisateur
  resource :profile, only: [:show, :edit, :update]

  # namespace pour le owner afin de le différencier du renter
  namespace :owner do
    resources :costumes, only: [:index, :show, :new, :create]
    resources :bookings, only: [:index, :show] do
      member do
        patch :accept
        patch :refuse
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :costume
end

app/models/costume.rb
class Costume < ApplicationRecord
  has_many :bookings
  belongs_to :user

  mount_uploader :image, PhotoUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :bookings # as renter
  # has_many :rented_costumes, through: :bookings, source: :costume # as renter

  has_many :costumes # as owner
  has_many :received_bookings, through: :costumes, source: :bookings #booking as an owner

  mount_uploader :avatar, PhotoUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def index
    @bookings = current_user.bookings
  end

  def create
    @booking = Booking.new(booking_params)
    @costume = Costume.find(params[:costume_id])

    @booking.costume = @costume
    @booking.user = current_user

    if @booking.save
      redirect_to bookings_path
    else
      render "costumes/show"
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:start_on, :end_on, :message)
  end
end

app/controllers/costumes_controller.rb
class CostumesController < ApplicationController
 skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    if params[:query].present?
      sql_query = "city ILIKE :query OR category ILIKE :query OR name ILIKE :query"
      @costumes = Costume.where(sql_query, query: "%#{params[:query]}%")
    else
      @costumes = Costume.all
    end
  end

  def show
    @costume = Costume.find(params[:id])
    @booking = Booking.new # On crée un objet vide pour simple_form
  end
end

app/controllers/owner/bookings_controller.rb
class Owner::BookingsController < ApplicationController

  def index
    @bookings = current_user.received_bookings
  end

  def accept
    @booking = Booking.find(params[:id])

    @booking.status = "accepted"
    @booking.save
    redirect_to owner_bookings_path
     # @costume.availability = false
  end

  def refuse
     @booking = Booking.find(params[:id])

    @booking.status = "refused"
    @booking.save
    redirect_to owner_bookings_path
  end

end

app/controllers/owner/costumes_controller.rb
class Owner::CostumesController < ApplicationController

  def index
    @costumes = current_user.costumes
  end

  # def show
  #   @costume = Costume.find(params[:id])
  #   @costume.user = current_user
  # end

  def new
    @costume = Costume.new
  end

  def create
    @costume = Costume.new(costume_params)
    @costume.user = current_user

    if @costume.save
      redirect_to owner_costumes_path
    else
      render :new
    end
  end

  private

  def costume_params
    params.require(:costume).permit(
      :name,
      :price,
      :description,
      :size,
      :category,
      :image,
      :city
    )
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div style="background-image: linear-gradient(-225deg, rgba(0,0,0,0.01) 20%, rgba(0,0,0,0.01) 20%),
  url('<%= image_path("background_home.jpg") %>');">
<div class="container">
 <div class="index-title text-center">
  <h1>List of all your bookings</h1>
 </div>

 <div class="background-white">
    <% @bookings.each do |booking| %>
      <div class="flat_card">
        <div class="element image">
          <%= cl_image_tag(booking.costume.image, width: 85, height: 100) %>
        </div>
        <div class="element content">
          <p><%= booking.costume.name.capitalize %></p>
          <p><%= booking.costume.price %><span> €/day</span></p>
        </div>
        <div class="element status">
          <p id="<%=booking.status %>"><%= booking.status %></p>
          <p><%= booking.start_on %> - <%= booking.end_on %></p>
        </div>
        <div class="element contact">
          <% if booking.status == "accepted" %>
            <p><%= booking.user.phone %></p>
          <% else %>
            <p><%= "..no contact yet.." %></p>
          <% end %>
         </div>
      </div>
    <% end %>
  </div>
</div>

app/views/costumes/index.html.erb
<div style="background-image: linear-gradient(-225deg, rgba(0,0,0,0.01) 20%, rgba(0,0,0,0.01) 20%),
  url('<%= image_path("background_home.jpg") %>');">

  <div class="container index-background">
    <div class="index-title text-center">
      <h1>Here is the list of all our costumes</h1>
    </div>

    <div class="background-white">
      <div class="row">
        <% @costumes.each do |costume| %>
          <div class="col-xs-8 col-sm-6 col-md-3">
            <% if costume.image.url.nil? %>
              <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= image_path "Kameleon-Logo.png", width: 200, height: 200, crop: :fill %>');">
            <% else %>
              <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3),rgba(0,0,0,0.2)), url('<%= cl_image_path costume.image, width: 500, height: 400, crop: :fill %>');">
            <% end %>
              <div class="card-category">
                <%= costume.category %></div>
              <div class="card-price">
                <span><%= costume.price %> € </span>
              </div>
              <div class="card-name">
                <h2><%= costume.name %></h2>
              </div>
              <div class="card-city">
                <%= costume.city %>
              </div>
              <%= link_to "", costume_path(costume), class: "card-link" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>

  </div>
</div>

app/views/costumes/show.html.erb
<!-- the show must go on ! -->
<div style="background-image: linear-gradient(-225deg, rgba(0,0,0,0.01) 20%, rgba(0,0,0,0.01) 20%),
  url('<%= image_path("background_home.jpg") %>');">
<div class="container">
  <h1>Costumes Details : </h1>
  <p>See the costume you just selected !</p>

  <div class="background-white">
    <div class="col-md-5">
      <% if @costume.image.url.nil? %>
        <%= image_tag("Kameleon-Logo.png") %>
      <% else %>
        <%= cl_image_tag @costume.image, width: 400, height: 450, crop: :fill %>
      <% end %>
      <p>Costume owner : <%= @costume.user.first_name %></p>
    </div>

    <div class="col-md-3">
      <p>Name : <%= @costume.name %></p>
      <p><%= @costume.price %> Euros</p>
      <br>
      <p>Description : </p>
      <p><%= @costume.description %></p>
      <br>
      <p>Size :<%= @costume.size %></p>
      <p>Category :<%= @costume.category %></p>
      <br>
      <p>City : <%= @costume.city %></p>
      <p> Available :
        <% if @costume.availability == true %>
            <%= "Yes" %>
          <% else %>
            <%= "No" %>
          <% end %>
      </p>
    </div>

    <div class="col-md-4">
      <%= simple_form_for [@costume, @booking] do |f| %>
        <%= f.input :start_on %>
        <%= f.input :end_on %>
        <%= f.input :message %>
        <%= f.submit "Rent", class: "btn btn-primary btn-block" %>
        <br>
      <% end %>

      <div class="btn-show-details">
        <div class="span2">
           <!-- List Alls -->
          <%= link_to 'See all costumes', costumes_path, class: "btn btn-success btn-block"  %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Kameleon</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>

  <body> <div class="wrapper-index-background">
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <!-- <div class="wrapper-index-background"> -->
      <%= yield %>
    <!-- </div> -->

    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <%= render 'shared/footer' %>

    </div>
  </body>
</html>

app/views/owner/bookings/index.html.erb
<div style="background-image: linear-gradient(-225deg, rgba(0,0,0,0.01) 20%, rgba(0,0,0,0.01) 20%),
  url('<%= image_path("background_home.jpg") %>');">
<div class="container">
  <div class="index-title text-center">
    <h1>Current rental booking </h1>
  </div>

  <div class="background-white">

    <% @bookings.each do |booking| %>

      <div class="flat_card">
        <div class="element image">
          <%= cl_image_tag(booking.costume.image, width: 85, height: 100) %>
        </div>

        <div class="element content">
          <p><%= booking.costume.name.capitalize %></p>
          <p><%= booking.costume.price %> <span> € / day</span></p>
        </div>

        <div class="element status">
          <p id="<%=booking.status %>"><%= booking.status %></p>
          <p><%= booking.start_on %> - <%= booking.end_on %></p>
        </div>

        <div class="element contact">

          <% if booking.status == "pending" %>
             <div class="span">
             <%= link_to 'Accept', accept_owner_booking_path(booking), method: :patch, class: "btn btn-success btn-block" %>
             <%= link_to 'Refuse', refuse_owner_booking_path(booking), method: :patch, class: "btn btn-danger btn-block"  %>
            </div>
          <% else %>
              <p><%= "" %></p>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/owner/costumes/_form.html.erb
 <!-- form ici !! -->
<div class="FormCostume">
  <%= simple_form_for [:owner, costume] do |f| %>
    <div class="col-md-4">
      <%= f.input :name %>
      <%= f.input :price, label:"Price (Euros)"%>
      <%= f.input :size %>
      <%= f.input :category, :collection => { "Animals" => "Animals", "Celebrities" => "Celebrities", "Public Events" => "Public Events", "Roles & Personages" => "Roles & Personages" }, :include_blank => 'Select a category', :multiple => true  %>
      <%= f.input :city %>
    </div>
    <div class="col-md-6">
      <%= f.input :image  %> <br><br><br>
      <%= f.input :description %>

    <%= f.submit 'Add a costume', class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/owner/costumes/index.html.erb
<div style="background-image: linear-gradient(-225deg, rgba(0,0,0,0.01) 20%, rgba(0,0,0,0.01) 20%),
  url('<%= image_path("background_home.jpg") %>');">
<div class="container">
  <h1>My costumes to rent</h1>
      <div class="col-xs col-xs-offset-3 col-sm-3 col-sm-offset-9 col-md-3 col-md-offset-9">
      <%= link_to "My bookings", owner_bookings_path, class: "btn btn-success btn-block"  %>
      </div>

  <div class="background-white">
    <div class="row">
      <% @costumes.each do |costume| %>
        <div class="col-xs-8 col-sm-6 col-md-3">
          <% if costume.image.url.nil? %>
            <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= image_path "Kameleon-Logo.png", width: 200, height: 200, crop: :fill %>');">
          <% else %>
            <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3),rgba(0,0,0,0.2)), url('<%= cl_image_path costume.image, width: 500, height: 400, crop: :fill %>');">
          <% end %>

            <div class="card-category">
              <%= costume.category %>
            </div>

            <div class="card-price col-xs-offset-3">
              <span><%= costume.price %> € </span>
            </div>

            <div class="card-name">
              <h2><%= costume.name %></h2>
            </div>

            <div class="card-city">
              <%= costume.city %>
            </div>

            <%= link_to "", costume_path(costume), class: "card-link" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/owner/costumes/new.html.erb
<div style="background-image: linear-gradient(-225deg, rgba(0,0,0,0.01) 20%, rgba(0,0,0,0.01) 20%),
  url('<%= image_path("background_home.jpg") %>');">
<div class="container">
  <h1>Add a new costume !</h1>

  <div class="background-white">
      <%= render 'form', costume: @costume %>
  </div>
</div>

app/views/pages/home.html.erb
<div class="banner text-center"
  style="background-image: linear-gradient(-225deg, rgba(0,0,0,0.2) 20%, rgba(0,0,0,0.2) 20%),
  url(<%= image_path 'background_home.jpg' %>)">
  <div class="banner-content">
    <h1>KAMELEON</h1>
    <%= image_tag "Kameleon-Logo.svg", class: "main_logo" %>
    <h2>Be the hero, pirate, unicorn you always wanted to be...</h2>
    <%= link_to "Get a Costume!", costumes_path, class: "btn btn-info btn-lg" %>
    <p></p>
    <p>Kameleon revolutionizes your way to party.<br>Forget the no-ending search for the perfect costume you are dreaming about.<br>Now, you will find easily the best costumes you never saw for a <strong>ridiculous renting price</strong>.<br>Go ahead.</p>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer"
  style="background-image: linear-gradient(-225deg, rgba(0,0,0,0.2) 20%, rgba(0,0,0,0.2) 20%),
  url(<%= image_path 'Deep_Space.jpg' %>)">
  <div class="footer-links">
    <!-- <a href="#"><i class="fa fa-github"></i></a> -->
    <a href="#"><i class="fa fa-instagram"></i></a>
    <a href="#"><i class="fa fa-facebook"></i></a>
    <a href="#"><i class="fa fa-twitter"></i></a>
    <!-- <a href="#"><i class="fa fa-linkedin"></i></a> -->
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fa fa-heart"></i> at Le Wagon
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon navbar-wagon-padding">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "Kameleon-Logo.svg", height: 50 %>
  <% end %>

  <%= form_tag costumes_path, class: "search-bar-navbar", method: :get do %>
    <%= text_field_tag :query,
      params[:query],
      class: "form-control",
      placeholder: "Find a costume"
    %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "Propose a costume", new_owner_costume_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "My bookings", bookings_path, class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= cl_image_tag (current_user.avatar), class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">

            <li>
              <%= link_to profile_path do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "My Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Log in"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>


  <!-- Dropdown list appearing on mobile only -->

  <div class="navbar-wagon-item hidden-md hidden-lg">

    <% if user_signed_in? %>

      <div class="dropdown">
        <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><%= link_to "Propose a costume", new_owner_costume_path %></li>
          <li><%= link_to "My bookings", bookings_path %></li>
          <li><%= link_to "My Profile", profile_path %></li>
          <li><%= link_to "Settings", "#" %></li>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
        </ul>
      </div>

    <% else %>

      <%= link_to t(".sign_in", default: "Log in"), new_user_session_path, class: "navbar-wagon-item-mobile navbar-wagon-link" %>
    <% end %>
  </div>
</div>